#include "server/object/code.h"
#include "server/object/configure.h"
#include "server/object/contest.h"
#include "server/object/discuss.h"
#include "server/object/error.h"
#include "server/object/filedata.h"
#include "server/object/file.h"
#include "server/object/inc.h"
#include "server/object/info.h"
#include "server/object/list.h"
#include "server/object/mail.h"
#include "server/object/news.h"
#include "server/object/problem.h"
#include "server/object/status.h"
#include "server/object/user.h"
#include "server/object/bufsize.h"

