#include "object/code.h"
#include "object/configure.h"
#include "object/contest.h"
#include "object/discuss.h"
#include "object/error.h"
#include "object/filedata.h"
#include "object/file.h"
#include "object/inc.h"
#include "object/info.h"
#include "object/list.h"
#include "object/mail.h"
#include "object/news.h"
#include "object/problem.h"
#include "object/status.h"
#include "object/user.h"
#include "object/bufsize.h"

