#ifndef _JUDGE_KERNEL_MODULE_KMMON_H__
#define _JUDGE_KERNEL_MODULE_KMMON_H__

#define __NR_kmmon 251
#define KMMON_MASK 0x08000000
#define KMMON_TRACEME 0
#define KMMON_CONTINUE 1
#define KMMON_KILL 2
#define KMMON_READMEM 3
#define KMMON_GETREG 4
#define KMMON_SIG 51

#endif

